### ISSUE TITLE
question about Optimal projection

### ISSUE THREAD

**Issue by laihongphuc** [LetianHuang/op43dgs#4]
Hi, thanks for the interesting work! My question is about Section 4. The error function R1 is not a function of μ' because for each 3D Gaussian, we have a unique μ' (derived from μ and matrix W). Additionally, R1 changes based on the projection plane. Therefore, I believe taking the derivative with respect to x0, rather than μ', is necessary to find the optimal projection direction. (x0 represents the projection plane in general.)

**Comment by LetianHuang** [comment]
Glad to hear your interest in this work!

We analyze the error function of the conventional projection of 3D-GS, where the projection plane is fixed at $z=1$, but the Gaussian mean is not fixed. Through analysis, we find that the error is minimized when the Gaussian mean coincides with the center of the projection plane. Based on this fact, we propose an optimal projection method where the center of the projection plane for each Gaussian coincides with the Gaussian mean. In fact, by fixing the mean $\mu^{'}$ and deriving the error function with respect to the center of the projection plane $x_0$, you can reach the same conclusion. This is because the error function is actually related to the relative position of $\mu^{'}$ and $x_0$, rather than their absolute positions.

Hope my response helps you better understand this paper.

**Comment by laihongphuc** [comment]
Thank you for the explanation!
