### ISSUE TITLE
Great Work! When will the fisheye rasterization algorithm be released?

### ISSUE THREAD

**Issue by TanVictory** [LetianHuang/op43dgs#7]

**Comment by LetianHuang** [comment]
Hello, we're glad to hear of your interest in this work. Unfortunately, we’re currently too busy to release the fisheye rasterization code. Additionally, our paper primarily demonstrates that the proposed projection can adapt to various camera models, rather than being specifically intended for this task. However, as mentioned in our paper, achieving this only requires modifying the coordinate transformations to match the camera model. If you need it urgently, you can adapt the existing [panorama](https://github.com/LetianHuang/op43dgs/tree/main/submodules/diff-gaussian-rasterization-panorama) or [pinhole](https://github.com/LetianHuang/op43dgs/tree/main/submodules/diff-gaussian-rasterization-pinhole) code (with corresponding adjustments to `backward.cu` if needed for training). The code includes detailed comments, so we’re confident you’ll be able to implement the modifications. Apologies once again for any inconvenience!

**Comment by yu-jingrui** [comment]
@TanVictory have you been able to derive the code for fisheye camera?

**Comment by yu-jingrui** [comment]
@LetianHuang  could you point out which part in the code (I suppose it's in `forward.cu` ?) is the coordinate transformations?

**Comment by LetianHuang** [comment]
I’m glad you’re interested in this work! Apologies for the delayed response due to a busy schedule. I have released the [submodule for the fisheye camera](https://github.com/LetianHuang/op43dgs/tree/main/submodules/diff-gaussian-rasterization-fisheye).
